import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useMotionValue, useReducedMotion, useSpring, useTransform } from 'framer-motion'
import { ArrowRight, Box, Check, Clapperboard, Image as ImageIcon, MapPin, MoveHorizontal, ScanLine, Sparkles, X } from 'lucide-react'
import Button from '../components/common/Button'
import Container from '../components/common/Container'
import realModelImage from '../assets/images/real 3d model image.jpg'
import villaFeatureImage from '../assets/images/portfolio-villa.png'
import villaDesertImage from '../assets/images/portfolio-villa-desert.png'
import officeImage from '../assets/images/portfolio-office.png'
import apartmentImage from '../assets/images/portfolio-apartment.png'
import hotelImage from '../assets/images/portfolio-hotel.png'
import retailImage from '../assets/images/portfolio-retail.png'
import headquartersImage from '../assets/images/portfolio-headquarters.png'

const projects = [
  ['Luxury Residential Villa', 'Residential Development', '3D Modeling · Rendering', villaDesertImage, 'aspect-[4/5]'],
  ['Commercial Office Tower', 'Commercial', 'Visualization · Walkthrough', officeImage, 'aspect-[4/3]'],
  ['Modern Apartment Complex', 'Multi-Family', 'Exterior · Marketing', apartmentImage, 'aspect-[3/4]'],
  ['Luxury Hotel', 'Hospitality', 'Interior · Rendering', hotelImage, 'aspect-[4/3]'],
  ['Retail Shopping Center', 'Retail Development', 'Modeling · Consulting', retailImage, 'aspect-[4/5]'],
  ['Corporate Headquarters', 'Workplace', 'Walkthrough · Marketing', headquartersImage, 'aspect-[4/3]'],
]
const stats = [['150+', 'Visualizations'], ['50M+', 'Development Value'], ['98%', 'Client Satisfaction'], ['25%', 'Fewer Revisions']]
const timeline = [[ScanLine, 'Blueprint'], [Box, 'Model'], [Sparkles, 'Render'], [Clapperboard, 'Animation'], [ImageIcon, 'Marketing'], [Check, 'Construction']]

function ProjectCard({ project, index, onOpen }) {
  const reducedMotion = useReducedMotion()
  const [title, category, services, image, ratio] = project
  const x = useMotionValue(0)
  const y = useMotionValue(0)
  const imageX = useSpring(useTransform(x, [-.5, .5], [-7, 7]), { stiffness: 120, damping: 25 })
  const imageY = useSpring(useTransform(y, [-.5, .5], [-7, 7]), { stiffness: 120, damping: 25 })
  const move = (event) => { const rect = event.currentTarget.getBoundingClientRect(); x.set((event.clientX - rect.left) / rect.width - .5); y.set((event.clientY - rect.top) / rect.height - .5) }
  return <motion.article onMouseMove={reducedMotion ? undefined : move} onMouseLeave={() => { x.set(0); y.set(0) }} initial={reducedMotion ? false : { opacity: 0, y: 36 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .55, delay: index * .08 }} className={`group relative overflow-hidden rounded-2xl border border-white/70 bg-white shadow-lg shadow-ink/[.08] ${ratio}`}><motion.img loading="lazy" src={image} alt={title} style={reducedMotion ? {} : { x: imageX, y: imageY }} className="h-full w-full scale-105 object-cover transition duration-700 group-hover:scale-115" /><div className="absolute inset-0 bg-gradient-to-t from-ink/90 via-ink/15 to-transparent opacity-80 transition group-hover:opacity-100" /><div className="absolute inset-x-5 bottom-5 translate-y-2 transition duration-300 group-hover:translate-y-0"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-brand">{category}</p><h2 className="mt-1 text-xl font-extrabold text-white">{title}</h2><p className="mt-1 text-xs text-white/75">{services}</p><button type="button" onClick={() => onOpen(project)} className="mt-4 inline-flex min-h-9 items-center gap-2 text-xs font-extrabold text-white outline-none transition hover:text-brand focus-visible:ring-2 focus-visible:ring-brand">View Project <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></button></div></motion.article>
}

function ProjectDetails({ project, onClose }) {
  const closeButton = useRef(null)
  const [title, category, services, image] = project
  useEffect(() => { closeButton.current?.focus(); const escape = (event) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, [onClose])
  return <motion.div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[80] grid place-items-center bg-ink/55 p-4 backdrop-blur-md"><motion.section role="dialog" aria-modal="true" aria-labelledby="project-details-title" initial={{ opacity: 0, scale: .9, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .96, y: 14 }} className="relative max-h-[90dvh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-white/70 bg-white shadow-2xl"><button ref={closeButton} type="button" onClick={onClose} aria-label="Close project details" className="absolute right-4 top-4 z-10 grid h-10 w-10 place-items-center rounded-full bg-ink/75 text-white transition hover:bg-brand focus:outline-none focus:ring-2 focus:ring-brand"><X size={18} /></button><div className="grid lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-64 overflow-hidden"><img src={image} alt={`${title} project`} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-ink/75 via-transparent to-transparent" /><p className="absolute bottom-6 left-6 text-xs font-extrabold uppercase tracking-[.16em] text-brand">{category}</p></div><div className="p-7 sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Project story</p><h2 id="project-details-title" className="mt-3 text-4xl font-extrabold tracking-[-.05em] text-ink">{title}</h2><p className="mt-5 text-sm leading-7 text-slate-600">This visualization was developed to give stakeholders a more immediate, confident understanding of the project before construction. It turns design intent into a visual story that supports approvals, presentations, and buyer conversations.</p><dl className="mt-7 grid gap-4 border-y border-slate-100 py-6 text-sm"><div><dt className="font-extrabold text-ink">Category</dt><dd className="mt-1 text-slate-600">{category}</dd></div><div><dt className="font-extrabold text-ink">Services used</dt><dd className="mt-1 text-slate-600">{services}</dd></div></dl><Button to="/contact" className="mt-7">Discuss a Similar Project <ArrowRight size={16} /></Button></div></div></motion.section></motion.div>
}

function ComparisonSlider() {
  const [position, setPosition] = useState(35)
  const direction = useRef(1)
  useEffect(() => { const timer = setInterval(() => setPosition((value) => { if (value >= 78) direction.current = -1; if (value <= 22) direction.current = 1; return value + direction.current }), 45); return () => clearInterval(timer) }, [])
  return <div className="relative aspect-[16/9] overflow-hidden rounded-2xl border border-white/50 bg-ink shadow-2xl shadow-ink/15"><img src={villaFeatureImage} alt="Photorealistic luxury villa rendering" className="absolute inset-0 h-full w-full object-cover" /><div style={{ clipPath: `inset(0 ${100 - position}% 0 0)` }} className="absolute inset-0 overflow-hidden bg-[#071e33]"><img src={realModelImage} alt="Architectural model and blueprint" className="h-full w-full object-cover" /><div className="blueprint-grid absolute inset-0 opacity-45" /></div><div style={{ left: `${position}%` }} className="pointer-events-none absolute inset-y-0 z-10 -translate-x-1/2 border-l-2 border-white"><span className="absolute left-1/2 top-1/2 grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-white/60 bg-ink text-white shadow-xl"><MoveHorizontal size={19} /></span></div><div className="absolute bottom-5 left-5 z-10 rounded-full bg-ink/75 px-3 py-1.5 text-[10px] font-extrabold tracking-[.15em] text-white backdrop-blur">BEFORE · MODEL</div><div className="absolute bottom-5 right-5 z-10 rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-extrabold tracking-[.15em] text-ink backdrop-blur">AFTER · RENDER</div><input aria-label="Reveal photorealistic render" type="range" min="0" max="100" value={position} onChange={(event) => setPosition(Number(event.target.value))} className="absolute inset-0 z-20 h-full w-full cursor-ew-resize opacity-0" /></div>
}

export default function PortfolioPage() {
  const reducedMotion = useReducedMotion()
  const [selectedProject, setSelectedProject] = useState(null)
  const heading = 'Featured Projects That Turn Vision Into Reality'.split(' ')
  return <div className="relative overflow-hidden"><div className="blueprint-grid pointer-events-none absolute inset-0 opacity-20" /><section className="relative py-20 text-center lg:py-28"><Container><motion.p initial={reducedMotion ? false : { opacity: 0, y: 12 }} animate={reducedMotion ? {} : { opacity: 1, y: 0 }} className="text-xs font-extrabold uppercase tracking-[.18em] text-brand">Project showcase</motion.p><h1 className="mx-auto mt-5 max-w-5xl text-4xl font-extrabold leading-[1.08] tracking-[-.055em] text-ink sm:text-6xl">{heading.map((word, index) => <motion.span key={`${word}-${index}`} initial={reducedMotion ? false : { opacity: 0, y: 22 }} animate={reducedMotion ? {} : { opacity: 1, y: 0 }} transition={{ delay: .1 + index * .065, duration: .45 }} className="mr-[.24em] inline-block last:mr-0">{word}</motion.span>)}</h1><motion.p initial={reducedMotion ? false : { opacity: 0, y: 16 }} animate={reducedMotion ? {} : { opacity: 1, y: 0 }} transition={{ delay: .55 }} className="mx-auto mt-6 max-w-3xl text-base leading-7 text-slate-600">Every visualization tells the story of a project before construction begins. Explore how our architectural visualization services help developers, architects, and investors communicate ideas with clarity and confidence.</motion.p></Container></section>
    <section className="relative pb-20 lg:pb-28"><Container><motion.article initial={reducedMotion ? false : { opacity: 0, y: 28 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true }} className="overflow-hidden rounded-3xl border border-white/70 bg-white/85 shadow-2xl shadow-ink/10 backdrop-blur"><div className="grid lg:grid-cols-[1.2fr_.8fr]"><div className="group relative min-h-[390px] overflow-hidden"><img src={villaFeatureImage} alt="Luxury Residential Villa visualization" className="h-full w-full object-cover transition duration-1000 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-tr from-ink/70 via-transparent to-brand/15" /><div className="absolute bottom-6 left-6 rounded-xl border border-white/20 bg-ink/75 p-4 text-white backdrop-blur"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-brand">Featured project</p><h2 className="mt-1 text-2xl font-extrabold">Luxury Residential Villa</h2><p className="mt-2 flex items-center gap-1.5 text-xs text-white/80"><MapPin size={14} className="text-brand" />Texas, USA · Residential Development</p></div></div><div className="p-7 sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">A clear path to approval</p><p className="mt-5 text-sm leading-7 text-slate-600">This project transformed traditional architectural drawings into a photorealistic visualization that allowed stakeholders and investors to explore the future property before construction. The immersive presentation improved communication, accelerated approvals, and strengthened buyer confidence.</p><dl className="mt-7 grid gap-5 border-y border-cyan-100 py-6 text-sm"><div><dt className="font-extrabold text-ink">Development Type</dt><dd className="mt-1 text-slate-600">Luxury Residential</dd></div><div><dt className="font-extrabold text-ink">Services</dt><dd className="mt-1 leading-6 text-slate-600">Architectural 3D Modeling · Photorealistic Rendering · Interior Visualization · Virtual Walkthrough</dd></div><div><dt className="font-extrabold text-ink">Duration</dt><dd className="mt-1 text-slate-600">4 Weeks</dd></div></dl><a href="#comparison" className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-brand transition hover:text-ink">See the transformation <ArrowRight size={16} /></a></div></div></motion.article></Container></section>
    <section id="comparison" className="relative bg-white py-20 lg:py-28"><Container><div className="grid items-end gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Before & after</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.05em] text-ink">Move from plan to certainty.</h2><p className="mt-5 text-sm leading-7 text-slate-600">Drag across the image to reveal how architectural plans become an immersive, investor-ready representation of the finished space.</p></div><ComparisonSlider /></div></Container></section>
    <section className="relative bg-white py-20 lg:py-28"><Container><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">More project stories</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.05em] text-ink">Built for every scale of vision.</h2></div><div className="mt-12 columns-1 gap-5 sm:columns-2 lg:columns-3">{projects.map((project, index) => <div key={project[0]} className="mb-5 break-inside-avoid"><ProjectCard project={project} index={index} onOpen={setSelectedProject} /></div>)}</div></Container></section>
    <section className="relative bg-[#e9fbfb] py-16"><Container><div className="grid gap-8 text-center sm:grid-cols-2 lg:grid-cols-4">{stats.map(([value, label], index) => <motion.div key={label} initial={reducedMotion ? false : { opacity: 0, y: 14 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .07 }}><p className="text-3xl font-extrabold text-brand">{value}</p><p className="mt-1 text-xs font-bold text-slate-600">{label}</p></motion.div>)}</div><div className="mt-14 flex flex-wrap justify-center gap-3">{timeline.map(([Icon, label], index) => <div key={label} className="flex items-center gap-3"><div className="flex items-center gap-2 rounded-full border border-brand/20 bg-white px-3 py-2 text-xs font-bold text-ink shadow-sm"><Icon size={15} className="text-brand" />{label}</div>{index < timeline.length - 1 && <ArrowRight size={14} className="hidden text-brand sm:block" />}</div>)}</div></Container></section>
    <section className="relative bg-ink py-20 text-center text-white"><div className="blueprint-grid absolute inset-0 opacity-20" /><Container className="relative"><h2 className="mx-auto max-w-3xl text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Ready To Visualize Your Next Development?</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-slate-300">Whether you are planning a residential project, commercial development, or investor presentation, our visualization services help you make informed decisions before construction begins.</p><Button to="/contact" className="mt-8">Start Your Project <ArrowRight size={16} /></Button></Container></section>
  <AnimatePresence>{selectedProject && <ProjectDetails project={selectedProject} onClose={() => setSelectedProject(null)} />}</AnimatePresence></div>
}
