import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useMotionValue, useReducedMotion, useSpring, useTransform } from 'framer-motion'
import { ArrowRight, Box, Check, Clapperboard, Compass, Image, Lightbulb, MonitorPlay, X } from 'lucide-react'
import Button from '../components/common/Button'
import Container from '../components/common/Container'
import aboutImage from '../assets/images/about-blueprint-reality.png'
import heroImage from '../assets/images/architectural-hero.png'
import towerImage from '../assets/images/commercial-tower.png'
import interiorImage from '../assets/images/luxury-interior.png'
import serviceImageOne from '../assets/images/service1image (1).png'
import serviceImageTwo from '../assets/images/service1image (2).png'

const services = [
  [Box, 'Architectural 3D Modelling', 'We convert technical drawings, CAD files, and architectural plans into highly accurate three-dimensional digital models that allow teams to understand every structural detail before construction begins.', aboutImage],
  [Lightbulb, 'Photorealistic Rendering', 'Our high-end rendering process creates realistic images with refined lighting, materials, reflections, landscaping, and environmental detail—long before the project is built.', heroImage],
  [Image, 'Interior & Exterior Visualization', 'Experience every interior and exterior space before construction. We reveal layouts, materials, furniture, natural lighting, and landscaping with exceptional realism.', interiorImage],
  [Clapperboard, 'Virtual Walkthroughs', 'Cinematic walkthrough animations help clients, investors, and stakeholders understand every space before it is built, speeding approvals and building buyer confidence.', serviceImageOne],
  [MonitorPlay, 'Real Estate Marketing Visuals', 'Premium visual assets for websites, social media, investor presentations, and property launches that help developers generate stronger buyer engagement before completion.', serviceImageTwo],
  [Compass, 'Design Review & Visualization Consulting', 'We work alongside project teams to identify design issues early through realistic visualization, reducing costly revisions and minimizing construction risk.', towerImage],
]

function ServiceCard({ service, index, onOpen }) {
  const reducedMotion = useReducedMotion()
  const [Icon, title, description, image] = service
  const pointerX = useMotionValue(0)
  const pointerY = useMotionValue(0)
  const rotateX = useSpring(useTransform(pointerY, [-.5, .5], [1.5, -1.5]), { damping: 24, stiffness: 150 })
  const rotateY = useSpring(useTransform(pointerX, [-.5, .5], [-1.5, 1.5]), { damping: 24, stiffness: 150 })
  function trackPointer(event) { const rect = event.currentTarget.getBoundingClientRect(); pointerX.set((event.clientX - rect.left) / rect.width - .5); pointerY.set((event.clientY - rect.top) / rect.height - .5) }
  return <motion.article onMouseMove={reducedMotion ? undefined : trackPointer} onMouseLeave={() => { pointerX.set(0); pointerY.set(0) }} style={reducedMotion ? {} : { rotateX, rotateY, transformPerspective: 1000 }} initial={reducedMotion ? false : { opacity: 0, y: 60, scale: .9 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0, scale: 1 }} viewport={{ once: true, amount: .12 }} transition={{ delay: index * .12, duration: .65, ease: [0.22, 1, 0.36, 1] }} className="group relative overflow-hidden rounded-2xl border border-white/70 bg-white/80 shadow-lg shadow-ink/[.07] backdrop-blur transition duration-300 hover:-translate-y-2 hover:border-brand/50 hover:shadow-2xl hover:shadow-brand/15"><div className="relative aspect-[16/9] overflow-hidden"><img loading="lazy" src={image} alt={title} className="h-full w-full object-cover transition duration-700 group-hover:scale-110" /><img loading="lazy" src={aboutImage} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-35 mix-blend-screen transition duration-700 group-hover:scale-105 group-hover:opacity-0" /><div className="absolute inset-0 bg-gradient-to-t from-ink/70 via-transparent to-transparent" /><div className="absolute bottom-4 left-5 flex items-center gap-2 text-white"><span className="grid h-9 w-9 place-items-center rounded-lg border border-white/20 bg-brand/85 backdrop-blur"><Icon size={18} /></span><span className="text-[10px] font-extrabold tracking-[.16em]">VISUALIZATION SERVICE</span></div></div><div className="relative p-7"><span className="absolute left-0 top-7 h-8 w-0.5 bg-brand transition-all duration-300 group-hover:h-14" /><h2 className="text-xl font-extrabold tracking-[-.035em] text-ink">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p><button type="button" onClick={() => onOpen(service)} className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-brand outline-none transition hover:text-ink focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2">Explore More <ArrowRight size={16} className="transition-transform duration-300 group-hover:translate-x-1" /></button></div></motion.article>
}

function ServiceDetails({ service, onClose }) {
  const closeButton = useRef(null)
  const [Icon, title, description, image] = service
  useEffect(() => { closeButton.current?.focus(); const escape = (event) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, [onClose])
  return <motion.div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[80] grid place-items-center bg-ink/55 p-4 backdrop-blur-md"><motion.section role="dialog" aria-modal="true" aria-labelledby="service-details-title" initial={{ opacity: 0, scale: .9, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .96, y: 14 }} className="relative max-h-[90dvh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-white/70 bg-white shadow-2xl"><button ref={closeButton} type="button" onClick={onClose} aria-label="Close service details" className="absolute right-4 top-4 z-10 grid h-10 w-10 place-items-center rounded-full bg-ink/75 text-white transition hover:bg-brand focus:outline-none focus:ring-2 focus:ring-brand"><X size={18} /></button><div className="grid lg:grid-cols-[.95fr_1.05fr]"><div className="relative min-h-64 overflow-hidden"><img src={image} alt={`${title} visualization`} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-ink/75 via-transparent to-transparent" /><span className="absolute bottom-6 left-6 grid h-12 w-12 place-items-center rounded-xl bg-brand text-white"><Icon size={23} /></span></div><div className="p-7 sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Service details</p><h2 id="service-details-title" className="mt-3 text-4xl font-extrabold tracking-[-.05em] text-ink">{title}</h2><p className="mt-5 text-sm leading-7 text-slate-600">{description} Our team shapes every deliverable around your project’s goals, helping you move from technical information to a presentation everyone can understand.</p><div className="mt-7 grid gap-4 border-y border-slate-100 py-6 sm:grid-cols-2"><div><p className="text-xs font-extrabold uppercase tracking-[.13em] text-slate-400">Included</p><ul className="mt-3 space-y-2 text-sm text-slate-600"><li className="flex gap-2"><Check size={16} className="text-brand" />Project-specific refinement</li><li className="flex gap-2"><Check size={16} className="text-brand" />Stakeholder-ready assets</li></ul></div><div><p className="text-xs font-extrabold uppercase tracking-[.13em] text-slate-400">Typical timeline</p><p className="mt-3 text-sm font-bold text-ink">2–4 weeks</p><p className="mt-1 text-xs text-slate-500">Based on project scope and input readiness.</p></div></div><Button to="/contact" className="mt-7">Book a Consultation <ArrowRight size={16} /></Button></div></div></motion.section></motion.div>
}

export default function ServicesPage() {
  const reducedMotion = useReducedMotion()
  const [selectedService, setSelectedService] = useState(null)
  const heading = "Visualizing Tomorrow's Buildings Before They Exist".split(' ')
  return <div className="relative overflow-hidden"><div className="blueprint-grid pointer-events-none absolute inset-0 opacity-20" /><section className="relative py-20 text-center lg:py-28"><Container><motion.p initial={reducedMotion ? false : { opacity: 0, y: 12 }} animate={reducedMotion ? {} : { opacity: 1, y: 0 }} className="text-xs font-extrabold uppercase tracking-[.18em] text-brand">Architectural visualization services</motion.p><h1 className="mx-auto mt-5 max-w-5xl text-4xl font-extrabold leading-[1.08] tracking-[-.055em] text-ink sm:text-6xl">{heading.map((word, index) => <motion.span key={`${word}-${index}`} initial={reducedMotion ? false : { opacity: 0, y: 22 }} animate={reducedMotion ? {} : { opacity: 1, y: 0 }} transition={{ delay: .12 + index * .07, duration: .45 }} className="mr-[.24em] inline-block last:mr-0">{word}</motion.span>)}</h1><motion.p initial={reducedMotion ? false : { opacity: 0, y: 18 }} animate={reducedMotion ? {} : { opacity: 1, y: 0 }} transition={{ delay: .55, duration: .55 }} className="mx-auto mt-6 max-w-3xl text-base leading-7 text-slate-600">We transform architectural concepts into immersive 3D experiences that improve planning, reduce risk, and help developers, architects, builders, and investors make confident decisions before construction begins.</motion.p></Container></section><section className="relative pb-20 lg:pb-28"><Container><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{services.map((service, index) => <ServiceCard key={service[1]} service={service} index={index} onOpen={setSelectedService} />)}</div></Container></section><section className="relative border-y border-cyan-100 bg-ink py-20 text-center text-white"><div className="blueprint-grid absolute inset-0 opacity-20" /><Container className="relative"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Start with clarity</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-extrabold tracking-[-.05em] sm:text-5xl">Ready To Bring Your Vision To Life?</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-slate-300">Whether you’re planning a luxury residence, commercial development, or large-scale real estate project, our visualization solutions help you move forward with confidence before construction begins.</p><Button to="/contact" className="mt-8 shadow-brand/30">Book Your Consultation <ArrowRight size={16} /></Button></Container></section><AnimatePresence>{selectedService && <ServiceDetails service={selectedService} onClose={() => setSelectedService(null)} />}</AnimatePresence></div>
}
