import { ArrowRight } from 'lucide-react'
import Container from '../common/Container'
import Button from '../common/Button'
import SectionTitle from '../common/SectionTitle'
import Reveal from '../common/Reveal'
import heroImage from '../../assets/images/architectural-hero.png'
import towerImage from '../../assets/images/commercial-tower.png'
import interiorImage from '../../assets/images/luxury-interior.png'
const projects = [['Luxury Residential Villa', 'Exterior & Interior Visualization', heroImage, 'sm:col-span-2 sm:row-span-2'], ['Commercial Tower', '3D Modeling & Walkthrough', towerImage, ''], ['Skyline Penthouse', 'Interior Visualization', interiorImage, ''], ['Modern Apartment Development', 'Exterior & Amenities', heroImage, 'sm:col-span-2']]
export default function Portfolio() { return <section id="portfolio" className="py-16 lg:py-24"><Container><div className="grid gap-10 lg:grid-cols-[.68fr_1.32fr]"><Reveal><div><SectionTitle eyebrow="Our portfolio" title="Recent Visualization Projects" description="Explore how we help developers, architects, and investors turn ideas into successful realities." /><Button to="/portfolio" className="mt-8">View Full Portfolio <ArrowRight size={16} /></Button></div></Reveal><div className="grid auto-rows-[170px] gap-4 sm:grid-cols-3">{projects.map(([title, type, image, span], index) => <Reveal key={title} delay={index * .08} className={span}><article className="group relative h-full overflow-hidden rounded-xl bg-slate-200"><img loading="lazy" src={image} alt={title} className="h-full w-full object-cover transition duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-ink/80 via-ink/5 to-transparent transition group-hover:from-ink/90" /><div className="absolute inset-x-5 bottom-5 translate-y-2 transition duration-300 group-hover:translate-y-0"><p className="text-sm font-extrabold text-white">{title}</p><p className="mt-1 text-xs text-white/75">{type}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-brand opacity-0 transition group-hover:opacity-100">View Project <ArrowRight size={13} /></span></div></article></Reveal>)}</div></div></Container></section> }
