import { useEffect, useState } from 'react'
import CountUpModule from 'react-countup'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowLeft, ArrowRight, Play, Quote, Star } from 'lucide-react'
import Button from '../common/Button'
import Container from '../common/Container'
import heroImage from '../../assets/images/architectural-hero.png'
import videoPoster from '../../assets/images/luxury-interior.png'
import walkthroughVideo from '../../assets/videos/Create_an_elegant_looping_arch.mp4'

const testimonials = [
  { name: 'Michael Turner', role: 'Real Estate Developer', initials: 'MT', quote: 'BluePrint & Beyond completely changed how we presented our development to investors. Instead of relying on technical drawings, we were able to showcase a realistic 3D experience that helped everyone immediately understand the project. The visualization process saved us valuable time and reduced several costly revisions before construction began.' },
  { name: 'Sarah Collins', role: 'Architect', initials: 'SC', quote: 'The level of realism exceeded our expectations. Every material, lighting condition, and architectural detail looked incredibly accurate. Our clients gained confidence much faster because they could visualize the final result before construction even started.' },
  { name: 'Daniel Brooks', role: 'Construction Project Manager', initials: 'DB', quote: 'Communication between our design team, engineers, and stakeholders became significantly easier after using the visualization models. Everyone worked from the same vision, which reduced misunderstandings and accelerated project approvals.' },
  { name: 'Emily Carter', role: 'Property Marketing Director', initials: 'EC', quote: 'The walkthrough animations became one of our strongest sales tools. Buyers experienced the property months before completion, which increased engagement and helped our sales team present the project with much greater confidence.' },
]

const CountUp = CountUpModule.default ?? CountUpModule
const trustStats = [['150+', 'Projects Visualized'], ['$50M+', 'Development Value'], ['98%', 'Client Satisfaction'], ['40%', 'Fewer Design Changes']]

function TestimonialCard({ testimonial, position, onSelect }) {
  const reducedMotion = useReducedMotion()
  const active = position === 0
  return <motion.article layout onClick={onSelect} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onSelect() }} initial={reducedMotion ? false : { opacity: 0, y: 28 }} animate={{ opacity: active ? 1 : .55, scale: active ? 1 : .9, y: active ? 0 : 12 }} transition={{ type: 'spring', stiffness: 180, damping: 23 }} className={`group relative overflow-hidden rounded-3xl border p-7 text-left outline-none transition focus-visible:ring-4 focus-visible:ring-brand/40 sm:p-9 ${active ? 'z-10 border-brand/35 bg-white shadow-2xl shadow-ink/10' : 'cursor-pointer border-slate-200 bg-white/75 shadow-lg'}`}>
    <img src={heroImage} alt="" aria-hidden="true" className="absolute inset-0 -z-10 h-full w-full object-cover opacity-[.045] blur-sm" />
    <Quote className="absolute right-7 top-7 text-brand/20 transition duration-500 group-hover:rotate-6 group-hover:text-brand/35" size={54} fill="currentColor" />
    <div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-brand to-[#0d5f88] text-sm font-extrabold text-white shadow-lg shadow-brand/20 transition duration-500 group-hover:scale-110">{testimonial.initials}</span><div><h3 className="text-base font-extrabold text-ink">{testimonial.name}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{testimonial.role}</p></div></div>
    <div className="mt-7 flex gap-1 text-brand">{Array.from({ length: 5 }, (_, star) => <motion.span key={star} initial={reducedMotion ? false : { opacity: 0, scale: .3 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .08 + star * .06 }}><Star size={15} fill="currentColor" /></motion.span>)}</div>
    <blockquote className="mt-5 text-[15px] leading-7 text-slate-600">“{testimonial.quote}”</blockquote>
  </motion.article>
}

export default function Testimonials() {
  const reducedMotion = useReducedMotion()
  const [active, setActive] = useState(0)
  const [paused, setPaused] = useState(false)
  const [videoOpen, setVideoOpen] = useState(false)
  const words = 'Trusted By Professionals Who Build The Future'.split(' ')
  const goTo = (value) => setActive((value + testimonials.length) % testimonials.length)
  useEffect(() => { if (paused || reducedMotion) return undefined; const timer = setInterval(() => setActive((value) => (value + 1) % testimonials.length), 6000); return () => clearInterval(timer) }, [paused, reducedMotion])

  return <section id="testimonials" aria-labelledby="testimonials-title" className="relative overflow-hidden bg-white py-20 lg:py-28"><div className="blueprint-grid pointer-events-none absolute inset-0 opacity-[.12]" /><div className="stage-scan pointer-events-none absolute left-[15%] top-16 h-20 w-[60%] opacity-20" /><Container className="relative"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-brand">Testimonials</p><h2 id="testimonials-title" className="mt-4 text-4xl font-extrabold leading-[1.05] tracking-[-.055em] text-ink sm:text-5xl">{words.map((word, index) => <motion.span key={`${word}-${index}`} initial={reducedMotion ? false : { opacity: 0, y: 18 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }} className="mr-[.24em] inline-block last:mr-0">{word}</motion.span>)}</h2><motion.p initial={reducedMotion ? false : { opacity: 0, y: 18 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .3 }} className="mx-auto mt-6 max-w-3xl text-sm leading-7 text-slate-600">Every successful development begins with confidence. Here’s what clients say about working with BluePrint & Beyond 3D LLC and how our visualizations improved projects before construction began.</motion.p></div>
    <div className="mt-12 grid overflow-hidden rounded-2xl border border-cyan-100 bg-white/85 shadow-xl shadow-ink/5 sm:grid-cols-2 lg:grid-cols-4">{trustStats.map(([value, label], index) => <motion.div key={label} initial={reducedMotion ? false : { opacity: 0, y: 15 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .07 }} className="border-b border-cyan-100 p-6 text-center last:border-b-0 sm:[&:nth-child(2)]:border-l lg:border-b-0 lg:border-l lg:first:border-l-0"><p className="text-3xl font-extrabold text-brand"><CountUp end={Number(value.replace(/[^0-9]/g, ''))} enableScrollSpy suffix={value.replace(/[0-9]/g, '')} /></p><p className="mt-1 text-[11px] font-bold text-slate-600">{label}</p></motion.div>)}</div>
    <div onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} className="mt-14"><div className="grid items-center gap-5 lg:grid-cols-3">{[-1, 0, 1].map((position) => { const index = (active + position + testimonials.length) % testimonials.length; return <div key={`${index}-${position}`} className={position === 0 ? 'lg:col-span-1' : 'hidden lg:block'}><TestimonialCard testimonial={testimonials[index]} position={position} onSelect={() => goTo(index)} /></div> })}</div><div className="mt-7 flex items-center justify-center gap-4"><button type="button" onClick={() => goTo(active - 1)} aria-label="Previous testimonial" className="grid h-10 w-10 place-items-center rounded-full border border-slate-200 text-ink transition hover:border-brand hover:bg-brand hover:text-white"><ArrowLeft size={17} /></button><div className="flex gap-2">{testimonials.map((item, index) => <button key={item.name} type="button" onClick={() => goTo(index)} aria-label={`Show testimonial from ${item.name}`} className={`h-2 rounded-full transition-all ${active === index ? 'w-7 bg-brand' : 'w-2 bg-slate-300 hover:bg-brand/60'}`} />)}</div><button type="button" onClick={() => goTo(active + 1)} aria-label="Next testimonial" className="grid h-10 w-10 place-items-center rounded-full border border-slate-200 text-ink transition hover:border-brand hover:bg-brand hover:text-white"><ArrowRight size={17} /></button></div></div>
    <motion.article initial={reducedMotion ? false : { opacity: 0, y: 24 }} whileInView={reducedMotion ? {} : { opacity: 1, y: 0 }} viewport={{ once: true }} className="mt-16 grid overflow-hidden rounded-3xl border border-white/80 bg-ink shadow-2xl shadow-ink/15 lg:grid-cols-[1fr_.9fr]"><button type="button" onClick={() => setVideoOpen(true)} className="group relative min-h-64 overflow-hidden text-left"><img loading="lazy" src={videoPoster} alt="Luxury residential visualization preview" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-ink/45 transition group-hover:bg-ink/30" /><span className="absolute inset-0 grid place-items-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-white/90 text-brand shadow-2xl transition group-hover:scale-110"><Play size={24} fill="currentColor" /></span></span></button><div className="flex flex-col justify-center p-8 text-white sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">Featured client story</p><h3 className="mt-4 text-3xl font-extrabold leading-tight tracking-[-.04em]">Watch How Visualization Helped Transform A Luxury Residential Development</h3><p className="mt-4 text-sm leading-7 text-slate-300">See how a planned residence becomes an experience that is easier to review, communicate, and confidently present.</p><button type="button" onClick={() => setVideoOpen(true)} className="mt-7 inline-flex items-center gap-2 self-start text-sm font-extrabold text-brand transition hover:text-white">Watch story <ArrowRight size={16} /></button></div></motion.article>
    <div className="mx-auto mt-14 max-w-3xl text-center"><p className="text-lg font-semibold leading-8 text-ink">From luxury residences to commercial developments, our visualization solutions help clients reduce uncertainty, improve collaboration, and move into construction with confidence.</p><Button to="/contact" className="group mt-7">Book Your Consultation <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></Button></div>
  </Container><AnimatePresence>{videoOpen && <motion.div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setVideoOpen(false) }} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[80] grid place-items-center bg-ink/70 p-5 backdrop-blur"><motion.section role="dialog" aria-modal="true" aria-label="Client story video" initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .96 }} className="w-full max-w-4xl overflow-hidden rounded-2xl bg-ink shadow-2xl"><video autoPlay muted controls playsInline preload="metadata" poster={videoPoster} className="aspect-video w-full object-cover"><source src={walkthroughVideo} type="video/mp4" /></video><div className="flex items-center justify-between p-4 text-sm font-bold text-white"><span>Luxury residential client story</span><button type="button" onClick={() => setVideoOpen(false)} className="text-brand hover:text-white">Close</button></div></motion.section></motion.div>}</AnimatePresence></section>
}
